#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Nov 27 19:02:49 2019
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from list_dialog import list_dialog


class MyApp(wx.App):
	def OnInit(self):
		self.list_dialog = list_dialog(None, wx.ID_ANY, "")
		self.SetTopWindow(self.list_dialog)
		self.list_dialog.ShowModal()
		self.list_dialog.Destroy()
		return True

# end of class MyApp

if __name__ == "__main__":
	app = MyApp(0)
	app.MainLoop()
