# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Thu Jun  6 12:07:28 2019
#

import os
import wx
from . import icons
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

# TODO: Use art provider for icons
# TODO: Forward events

class dir_picker(wx.Panel):
	def __init__(self, parent, id=wx.ID_ANY, value="", pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.TAB_TRAVERSAL, name=b"dir_picker", default_directory=os.getcwd()):
		self._parent = parent
		self.initial_value = value
		self.default_directory = default_directory
		
		wx.Panel.__init__(self, self._parent, id=wx.ID_ANY, pos=pos, size=size, style=style, name=name)
		self.dir_value = wx.TextCtrl(self, wx.ID_ANY, "")
		self.clear_btn = wx.BitmapButton(self, wx.ID_ANY, icons.get_button_icon("ART_GO_BACK", 16))
		self.browse_btn = wx.BitmapButton(self, wx.ID_ANY, icons.get_button_icon("ART_FOLDER_OPEN", 16))
		
		self.textctrl_width = 150
		self.height = 29
		
		self.__set_properties()
		self.__do_layout()
		
		self.Bind(wx.EVT_BUTTON, self.on_clear, self.clear_btn)
		self.Bind(wx.EVT_BUTTON, self.on_browse, self.browse_btn)
		
		
		return
		
		
		# begin wxGlade: dir_picker.__init__
		kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self.dir_value = wx.TextCtrl(self, wx.ID_ANY, "")
		self.clear_btn = wx.BitmapButton(self, wx.ID_ANY, wx.NullBitmap)
		self.browse_btn = wx.BitmapButton(self, wx.ID_ANY, wx.NullBitmap)

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.on_clear, self.clear_btn)
		self.Bind(wx.EVT_BUTTON, self.on_browse, self.browse_btn)
		# end wxGlade
	
	def __set_properties(self):
		# begin wxGlade: dir_picker.__set_properties
		self.dir_value.SetMinSize((-1, 29))
		self.clear_btn.SetMinSize((29, 29))
		self.browse_btn.SetMinSize((29, 29))
		# end wxGlade
	#self.dir_value.SetMinSize((self.textctrl_width, self.height))
	#self.clear_btn.SetMinSize((self.height, self.height))
	#self.browse_btn.SetMinSize((self.height, self.height))
	#self.SetMinSize((self.textctrl_width + 5 + (2*self.height), self.height+5))
	
	def __do_layout(self):
		# begin wxGlade: dir_picker.__do_layout
		sizer = wx.BoxSizer(wx.HORIZONTAL)
		sizer_5 = wx.BoxSizer(wx.VERTICAL)
		sizer_5.Add(self.dir_value, 1, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
		sizer.Add(sizer_5, 1, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
		sizer.Add(self.clear_btn, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer.Add(self.browse_btn, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		self.SetSizer(sizer)
		sizer.Fit(self)
		self.Layout()
		# end wxGlade
	
	def set_textctrl_width(self, width):
		self.textctrl_width = width
		self.__set_properties()
		self.Layout()
	
	def set_height(self, height):
		self.height = height
		self.__set_properties()
		self.Layout()
	
	def on_clear(self, event):  # wxGlade: dir_picker.<event_handler>
		self.dir_value.Clear()
		self.dir_value.SetFocus()
		event.Skip()
	
	def on_browse(self, event):  # wxGlade: dir_picker.<event_handler>
		dlg = wx.DirDialog(None, "Choose a directory:", style=wx.DD_DEFAULT_STYLE | wx.DD_NEW_DIR_BUTTON,
						   defaultPath=self.default_directory)
		if dlg.ShowModal() == wx.ID_OK:
			self.dir_value.SetValue((dlg.GetPath()))
		dlg.Destroy()
		self.dir_value.SetFocus()
		event.Skip()
	
	def get_value(self):
		return self.dir_value.GetValue()
	
	def reset_value(self):
		return self.dir_value.SetValue(self.initial_value)
# end of class dir_picker

